### ISSUE TITLE
PDF Library bestimmen

### ISSUE THREAD

**Issue by kluckow** [kluckow/mittelstufenprojekt#4]

**Comment by kluckow** [comment]
Also wie gesagt, ich kann das mit der Apache FOP Library machen. Allerdings muss ich dafür mehr über die Struktur des PDF und die Daten wissen.

**Comment by hekmekk** [comment]
Falls wir iText verwenden wollen

http://developers.itextpdf.com/content/itext-7-jump-start-tutorial
