### ISSUE TITLE
GUI implementieren

### ISSUE THREAD

**Issue by kluckow** [kluckow/mittelstufenprojekt#7]
- [x] IDs für Combobox und Checkbox setzen (combo_abteilung, combo_ausbildungsberuf, combo_ausbildungsjahr, checkbox_inhalte, etc.)
- [x] Combobox mit Einträgen füllen: [Video-Tutorial](https://www.youtube.com/watch?v=zAKAK_IOq80)
- [x] Toolbar entfernen
- [x] Formular nach erfolgreicher Generierung des PDF zurücksetzen
- [x] Fix: Ausbildungsberuf soll erst nach Auswählen der Abteilung auswählbar sein
- [x] Setze PDFFilters
- [x] Form: id statt name übergeben

**Comment by hekmekk** [comment]
Wollen wir JavaFX benutzen? Da gibt es ein Tool, mit dem man das ganze zusammenklicken kann. Hab's allerdings noch nie benutzt.

http://www.oracle.com/technetwork/java/javafxscenebuilder-1x-archive-2199384.html

**Comment by kluckow** [comment]
Ja, habe damit auch schon gearbeitet. ich kümmere mich um die GUI.

**Comment by kluckow** [comment]
![preview](https://cloud.githubusercontent.com/assets/10063698/16192599/87ab5e9c-36ea-11e6-99f7-b519aef6f44f.PNG)
So sieht es bisher aus.

**Comment by kluckow** [comment]
![preview](https://cloud.githubusercontent.com/assets/10063698/16192746/620b8d5a-36eb-11e6-9e1c-42183a8eb660.PNG)
Diesmal mit Button.

**Comment by kluckow** [comment]
Screenshot veraltet, Menubar existiert nicht mehr, da keine Verwendung.
